# Generated by Django 4.2.16 on 2025-02-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textentry',
            name='content',
        ),
        migrations.RemoveField(
            model_name='textentry',
            name='superuser',
        ),
        migrations.RemoveField(
            model_name='textentry',
            name='title',
        ),
        migrations.AddField(
            model_name='textentry',
            name='text',
            field=models.TextField(default='Default Text'),
        ),
    ]
