# Generated by Django 4.2.16 on 2025-02-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0003_deletedtextentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textentry',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
